const AWS = {
    REGION: process.env.REACT_APP_REGION,
    USER_POOL_ID: process.env.REACT_APP_COGNITO_USER_POOL_ID,
    USER_POOL_APP_CLIENT_ID:
        process.env.REACT_APP_COGNITO_USER_POOL_APP_CLIENT_ID,
    COGNITO_DOMAIN: process.env.REACT_APP_COGNITO_DOMAIN,
    GOOGLE_CLIENT_ID: process.env.REACT_APP_GOOGLE_CLIENT_ID,
}
console.log(AWS)

export default AWS
