name: deploy

on:
    workflow_dispatch:
permissions:
    id-token: write
    contents: read
    pull-requests: write
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: branch check (main only)
              if: github.ref!='refs/heads/main'
              run: |
                  echo "terraform apply runs on main branch only !"
                  exit 1
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  role-to-assume: ${{secrets.AWS_ROLE_ARN}}
                  aws-region: ap-northeast-1
            - name: install
              run: npm install
            - name: build
              run: npm run build
            - name: deploy to s3
              run: aws s3 cp /build s3://music-tools-frontend-prod/
