name: deploy

on:
    workflow_dispatch:
permissions:
    id-token: write
    contents: read
    pull-requests: write
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: branch check (main only)
              if: github.ref!='refs/heads/main'
              run: |
                  echo "this action runs on main branch only !"
                  exit 1
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  role-to-assume: ${{secrets.AWS_ROLE_ARN}}
                  aws-region: ap-northeast-1
            - name: set additional env vars for prod
              run: |
                  echo "REACT_APP_COGNITO_USER_POOL_ID=$(aws ssm get-parameter --output text --name '/music_tools/prod/frontend/cognito_user_pool_id' --query Parameter.Value)" >> $GITHUB_ENV
                  echo "REACT_APP_COGNITO_USER_POOL_APP_CLIENT_ID=$(aws ssm get-parameter --output text --name '/music_tools/prod/frontend/cognito_user_pool_app_client_id' --query Parameter.Value)" >> $GITHUB_ENV
                  echo "REACT_APP_COGNITO_DOMAIN=$(aws ssm get-parameter --output text --name '/music_tools/prod/frontend/cognito_domain' --query Parameter.Value)" >> $GITHUB_ENV
                  echo "REACT_APP_GOOGLE_CLIENT_ID=$(aws ssm get-parameter --output text --name '/music_tools/prod/frontend/google_oauth_client_id' --query Parameter.Value)" >> $GITHUB_ENV
            - name: append env var to .env.production
              run: |
                  echo "REACT_APP_COGNITO_USER_POOL_ID=$REACT_APP_COGNITO_USER_POOL_ID" >> .env.production
                  echo "REACT_APP_COGNITO_USER_POOL_APP_CLIENT_ID=$REACT_APP_COGNITO_USER_POOL_APP_CLIENT_ID" >> .env.production
                  echo "REACT_APP_COGNITO_DOMAIN=$REACT_APP_COGNITO_DOMAIN" >> .env.production
                  echo "REACT_APP_GOOGLE_CLIENT_ID=$REACT_APP_GOOGLE_CLIENT_ID" >> .env.production
            - name: install
              run: npm install
            - name: build
              env:
                  CI: false
              run: npm run build
            - name: deploy to s3
              run: aws s3 cp ./build s3://music-tools-frontend-prod/ --recursive
